require("ggplot2")
require(reshape2)
require(lme4)
require(lattice)
library(dplyr, warn.conflicts = FALSE)
require(tidyverse)
require("haven")
require(lsr)
require(plyr)
require(car)
library(latticeExtra)  
library(markdown)
library(knitr)
require(lubridate)
library(glue)
library(readr)
